import authcontroller from "./authController";
import homecontroller from "./homeController";
import usercontroller from "./userController";
import FindUsersContact from "./contactController";
import notifiController from "./notificationController";
export const auth = authcontroller;
export const home = homecontroller;
export const user = usercontroller;
export const contact = FindUsersContact;
export const notifi = notifiController;