module.exports = {
	DB_Connection: "mongodb",
	DB_Host: "127.0.0.1",
	DB_Post: 27017,
	DB_Name: "web_chat",
	DB_UserName: "",
	DB_PassWord: "",
	hostname: "localhost",
	port: 2505,
	MAIL_USER: "nvbinh.mern@gmail.com",
	MAIL_PASSWORD: "Binhviet2505",
	MAIL_HOST: "smtp.gmail.com",
	MAIL_PORT: 587,
	fbid: "986422321736643",
	fbsecret: "ddcd6e7a2a997a0d7aaec88d1fb50574",
	fbUrl: "http://localhost:2505/auth/facebook/callback",
	key: "vietbinh",
	secret: "myvietbinh",
	LimitCT: 2,
	LimitNT: 10,
	LimitTaken: 10,
	LimitMess: 20,
	avatar_directory: 'src/public/images/users',
	avatar_type: ['image/png', 'image/jpg', 'image/jpeg'],
	avatar_limit_size: 1048576,
	general_avatar_group_chat: "group-avatar-nvb.png",
	image_message_directory: "src/public/images/chat/message",
	attachment_message_directory: "src/public/images/chat/message",
	image_message_type: ['image/png', 'image/jpg', 'image/jpeg'],
	image_message_limit_size: 1048576,
	attachment_message_limit_size: 1048576,
	defaultMaxListeners: 40,
};